version: "3.8"
services:
  www:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    networks:
      - "default-network"
    volumes:
      - "/home/bruno/Everything:/var/Everything"
    ports:
      - "8080:8080"
    depends_on:
      - "db"
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    expose:
      - "3306"
    networks:
      - "default-network"
networks:
  default-network:
    driver: bridge
