FROM debian:buster-slim
COPY . /usr/local/src/container
RUN /usr/local/src/container/scripts/install-wp.sh
COPY ./nginx.conf /etc/nginx/nginx.conf
COPY ./scripts/docker-entrypoint.sh /
ENTRYPOINT ["/docker-entrypoint.sh"]
